Week2 600-700 translation
cs50rus/cs50rus pull request #11
Opened 2020-07-21 20:36 UTC by DevAleks

Added a translation of the week2, parts 600-700.
Please additionally check parts:
613
616
617
633
660
692
693
694
698

My level of C now is mach more badly than about 25 years before :)

2020-07-21 22:30 UTC, Illumaria requested changes

2020-07-21 22:30 UTC, Illumaria commented on cs50intro/week2/lecture1ru.srt
> +снаружи и изннутри,
снаружи внутрь,

2020-07-21 22:30 UTC, Illumaria commented on cs50intro/week2/lecture1ru.srt
> +АУДИТОРИЯ: Можете ли вы добавить [неразборчиво]?
Можно ли добавлять

2020-07-21 22:30 UTC, Illumaria commented on cs50intro/week2/lecture1ru.srt
> +Можете ли вы добавить другие переменные?
Можно ли добавлять

2020-07-21 22:30 UTC, Illumaria commented on cs50intro/week2/lecture1ru.srt
> +Я мог бы просто сделать запятую, что-нибудь в этом роде
я мог бы написать: запятая, что-то ещё,

2020-07-21 22:30 UTC, Illumaria commented on cs50intro/week2/lecture1ru.srt
> +еще, запятая, что-то еще, запятая.
запятая, что-то ещё, запятая.

2020-07-21 22:30 UTC, Illumaria commented on cs50intro/week2/lecture1ru.srt
> +И я бы просто взял один плейсхолдер
заполнитель

2020-07-21 22:30 UTC, Illumaria commented on cs50intro/week2/lecture1ru.srt
> +то
то первый

2020-07-21 22:30 UTC, Illumaria commented on cs50intro/week2/lecture1ru.srt
> +первый бы шел после первой запятой.
шёл бы после первой запятой.

2020-07-21 22:30 UTC, Illumaria commented on cs50intro/week2/lecture1ru.srt
> +АУДИТОРИЯ: Так вам нужен %s [НЕРАЗБОРЧИВО]
То есть нужно использовать %s

2020-07-21 22:30 UTC, Illumaria commented on cs50intro/week2/lecture1ru.srt
> +Просто призови меня.
просто подайте голос.

2020-07-21 22:30 UTC, Illumaria commented on cs50intro/week2/lecture1ru.srt
> +И если я когда-нибудь буду скучать
Если я случайно пропущу ваши руки

2020-07-21 22:30 UTC, Illumaria commented on cs50intro/week2/lecture1ru.srt
> +по твоей руке, то это будет просто сияние.
из-за всего этого яркого света,

2020-07-21 22:30 UTC, Illumaria commented on cs50intro/week2/lecture1ru.srt
> +поэтому я собираюсь принять его
поэтому воспользуюсь этим

2020-07-21 22:30 UTC, Illumaria commented on cs50intro/week2/lecture1ru.srt
> +эту конвенцию. -o hello.
знанием. -o hello.

2020-07-21 22:30 UTC, Illumaria commented on cs50intro/week2/lecture1ru.srt
> +с добавления stdio.h int main void
оставь include без перевода

2020-07-21 22:30 UTC, Illumaria commented on cs50intro/week2/lecture1ru.srt
> +сказать string answer get get_string,
Надо глянуть видео. Наверное, get должно переводиться.

2020-07-21 22:33 UTC, Illumaria commented
Перечитай, пожалуйста, внимательно свой текст. Исключительно русский вариант. Представь, что ты это зачитываешь на трансляции. :) Если чувствуешь, что не звучит – верный признак что-то поменять.

Есть пропущенный элемент (как минимум один, но я не всё смотрел) – двадцать какой-то.

2020-07-22 12:02 UTC, DevAleks commented
Дмитрий, спасибо за ревью! Постараюсь вечером все поправить. И буду смотреть видео следующий раз)

2020-07-22 13:05 UTC, Illumaria commented on cs50intro/week2/lecture1ru.srt
> +сказать string answer get get_string,
Там вон оно что, оказывается: он просто описАлся и, соответственно, оговорился. "get" можно выкинуть.

2020-07-25 11:34 UTC, DevAleks commented
Исправил и дополнил перевод.

2020-08-01 10:33 UTC, merged