1300-1400 translation
cs50rus/cs50rus pull request #13
Opened 2020-07-24 13:44 UTC by Illumaria

2020-07-25 10:53 UTC, HadesArchitect commented
Review in progress

2020-07-25 11:23 UTC, HadesArchitect requested changes
Пара мелких правок, не настаиваю (ну, кроме опечатки. Кстати, интересное словечко получилось!)

2020-07-25 11:23 UTC, HadesArchitect commented on cs50intro/week2/lecture1ru.srt
> +сверху вниз и слева направо.
```suggestion
скорее сверху вниз чем слева направо.
```
Он имеет в виду, что "высокий" код читать удобнее, чем "широкий" - notice the "more ... than"

2020-07-25 11:23 UTC, HadesArchitect commented on cs50intro/week2/lecture1ru.srt
> +Это архитекрутное решение.
```suggestion
Это архитектурное решение.
```
=) 

Хотя, если честно, здесь design не полностью корректно переводить как архитектурное, потому что в русском языке архитектура имеет более "высокоуровневое значение". То есть, делая код-ревью на русском языке, я бы так никогда не сказал. Может быть, есть лучший вариант?

2020-07-25 11:23 UTC, HadesArchitect commented on cs50intro/week2/lecture1ru.srt
> +с плавающей точкой, то есть
Перевод корректный, но, может быть, упростить до "чисел с запятой" или "десятичных дробей"? Потому что людей, которые забыли или никогда не знали математику, плавающая точка и действительные числа напугают.

Причем в других местах можно оставить, как есть, а вот вводить их лучше как более простую концепцию, мне кажется.

2020-07-26 13:16 UTC, Illumaria commented
@HadesArchitect Обновил эти места. Посмотри, пожалуйста.

2020-07-31 21:29 UTC, HadesArchitect approved these changes
lgtm

2020-07-31 21:30 UTC, merged